overlay: update rknpu to v1.3.0 for rk3399pro
 1. update galcore.ko (6.4.0.227915 030570c6)
       rk1808 base on kernel commit id:
           d81e5390d0921d7fb019f3a45ab08d5e0e1d2fb0
       rk1808 fedora:
           b75e99f54361dd71fe7896919076692ae97b7585
       rk3399pro/rk3399pro pcie:
           577aa02a6d309d0697db079c673baf0b815f5d53
2. update rknn_server to 1.3.0 (c4f8c233)
3. update librknn_runtime to 1.3.0 (0e1d4ea6)
4. New features:
    1) Add multi-channels-mean support
    2) New op: argmax argmin gru grucell log_softmax

Change-Id: I30601ca2945f3ce5add7327606a1e980556dd85b
Signed-off-by: Caesar Wang <wxt@rock-chips.com>

diff --git a/overlay-firmware/usr/bin/npu_upgrade b/overlay-firmware/usr/bin/npu_upgrade
--- a/overlay-firmware/usr/bin/npu_upgrade
+++ b/overlay-firmware/usr/bin/npu_upgrade
@@ -4,7 +4,7 @@ PROGRAM=${0##*/}
 #reset npu
 /usr/bin/npu_powerctrl -i
 /usr/bin/npu_powerctrl -o
-#sleep 1
+sleep 1
 
 if [ $# -ne 4 ]; then
 	echo 'Usage: '$PROGRAM' loader uboot trust boot'
@@ -17,9 +17,94 @@ LOADER=$DIR/$1
 UBOOT=$DIR/$2
 TRUST=$DIR/$3
 BOOT=$DIR/$4
-UBOOT_ADDR=0x40000
-TRUST_ADDR=0x40800
-BOOT_ADDR=0x20000
+UBOOT_ADDR=0x20000
+TRUST_ADDR=0x20800
+BOOT_ADDR=0x21000
+
+function download_func()
+{
+	local RET1=1
+	echo 'start to download loader...' >>  /tmp/npu.log
+	$UPGRADE_TOOL db $LOADER > /dev/null
+	if [ $? -ne 0 ]; then
+		echo 'failed to download loader!' >>  /tmp/npu.log
+		return $RET1;
+	fi
+	echo 'download loader ok' >>  /tmp/npu.log
+
+	sleep 1
+	echo 'start to wait loader...' >>  /tmp/npu.log
+	$UPGRADE_TOOL td > /dev/null
+	if [ $? -ne 0 ]; then
+		echo 'failed to wait loader!' >>  /tmp/npu.log
+		return $RET1
+	fi
+	echo 'loader is ready'  >>  /tmp/npu.log
+
+	echo 'start to write uboot...' >>  /tmp/npu.log
+	$UPGRADE_TOOL wl $UBOOT_ADDR $UBOOT > /dev/null
+	if [ $? -ne 0 ]; then
+		echo 'failed to write uboot!' >>  /tmp/npu.log
+		return $RET1
+	fi
+	echo 'write uboot ok' >>  /tmp/npu.log
+
+	echo 'start to write trust...'
+	$UPGRADE_TOOL wl $TRUST_ADDR $TRUST > /dev/null
+	if [ $? -ne 0 ]; then
+		echo 'failed to write trust!' >>  /tmp/npu.log
+		return $RET1
+	fi
+	echo 'write trust ok' >>  /tmp/npu.log
+
+	echo 'start to write boot...' >>  /tmp/npu.log
+	$UPGRADE_TOOL wl $BOOT_ADDR $BOOT > /dev/null
+	if [ $? -ne 0 ]; then
+		echo 'failed to write boot!' >>  /tmp/npu.log
+		return $RET1
+	fi
+	echo 'write boot ok' >>  /tmp/npu.log
+	RET1=0
+	return $RET1
+}
+
+function check_device_ready_func()
+{
+	echo 'start to wait device...' >  /tmp/npu.log
+	local i=0
+	local RET=1
+	while [ $i -lt 10 ]; do
+		$UPGRADE_TOOL ld > /dev/null
+		if [ $? -ne 0 ]; then
+			i=$((i+1))
+			echo $i
+			sleep 0.1
+		else
+			sleep 0.1
+			break
+		fi
+		if [ $i -eq 5 ]; then
+			/usr/bin/npu_powerctrl -o
+			sleep 3
+			echo 'reset npu to retry!!!' >> /tmp/npu.log
+		fi
+	done
+	if [ $i -ge 10 ]; then
+		echo 'failed to wait device!'  >>  /tmp/npu.log
+		return $RET
+	fi
+	echo 'device is ready' >>  /tmp/npu.log
+	RET=0
+	return $RET
+}
+
+function poweron_Npu_func()
+{
+	/usr/bin/npu_powerctrl -i
+	sleep 0.1
+	/usr/bin/npu_powerctrl -o
+	sleep 1
+}
 
 if [ ! -f $UPGRADE_TOOL ]; then
 	echo $UPGRADE_TOOL 'is not existed!'
@@ -46,72 +131,25 @@ if [ ! -f $BOOT ]; then
 	exit
 fi
 
-echo 'start to wait device...'
-i=0
-while [ $i -lt 10 ]; do
-	$UPGRADE_TOOL ld > /dev/null
-	if [ $? -ne 0 ]; then
-		i=$((i+1))
-		echo $i
-		sleep 0.01
-	else
-		break
-	fi
-	if [ $i -eq 5 ]; then
-		/usr/bin/npu_powerctrl -o
-		echo 'reset npu to retry!!!'
-	fi
-done
-if [ $i -ge 10 ]; then
-	echo 'failed to wait device!'
-	exit
+check_device_ready_func
+if [ $? = 1 ];then
+	echo "check_device_ready error!!!" >> /tmp/npu.log
+	poweron_Npu_func
+	check_device_ready_func
 fi
-echo 'device is ready'
 
-echo 'start to download loader...'
-$UPGRADE_TOOL db $LOADER > /dev/null
-if [ $? -ne 0 ]; then
-	echo 'failed to download loader!'
-	exit
+download_func
+if [ $? = 1 ];then
+	echo "reset download_func"
+	poweron_Npu_func
+	check_device_ready_func
+	download_func
 fi
-echo 'download loader ok'
 
-echo 'start to wait loader...'
-$UPGRADE_TOOL td > /dev/null
-if [ $? -ne 0 ]; then
-	echo 'failed to wait loader!'
-	exit
-fi
-echo 'loader is ready'
-
-echo 'start to write uboot...'
-$UPGRADE_TOOL wl $UBOOT_ADDR $UBOOT > /dev/null
-if [ $? -ne 0 ]; then
-	echo 'failed to write uboot!'
-	exit
-fi
-echo 'write uboot ok'
-
-echo 'start to write trust...'
-$UPGRADE_TOOL wl $TRUST_ADDR $TRUST > /dev/null
-if [ $? -ne 0 ]; then
-	echo 'failed to write trust!'
-	exit
-fi
-echo 'write trust ok'
-
-echo 'start to write boot...'
-$UPGRADE_TOOL wl $BOOT_ADDR $BOOT > /dev/null
-if [ $? -ne 0 ]; then
-	echo 'failed to write boot!'
-	exit
-fi
-echo 'write boot ok'
-
-echo 'start to run system...'
+echo 'start to run system...' >>  /tmp/npu.log
 $UPGRADE_TOOL rs $UBOOT_ADDR $TRUST_ADDR $BOOT_ADDR $UBOOT $TRUST $BOOT > /dev/null
 if [ $? -ne 0 ]; then
-	echo 'failed to run system!'
+	echo 'failed to run system!' >>  /tmp/npu.log
 	exit
 fi
-echo 'run system ok'
+echo 'run system ok' >>  /tmp/npu.log
